"""Framework detection and routing gateway.

Detects which documentation framework generated an HTML page and routes
to the appropriate converter.
"""

from .frameworks.base import BaseConverter
from .frameworks.mkdocs_material.converter import MkdocsMaterialConverter
from .frameworks.mkdocs_material.validator import get_version as _mkdocs_version


# Registry of supported framework converters (checked in order)
_CONVERTERS: list[type[BaseConverter]] = [
    MkdocsMaterialConverter,
]


class UnsupportedFrameworkError(Exception):
    """Raised when no converter can handle the given HTML."""


def detect_framework(html: str) -> BaseConverter | None:
    """Try each registered converter; return the first matching one."""
    for cls in _CONVERTERS:
        if cls.detect(html):
            return cls()
    return None


def get_converter(html: str) -> BaseConverter:
    """Detect and return the appropriate converter, or raise an error.

    Raises:
        UnsupportedFrameworkError: If no converter matches.
    """
    converter = detect_framework(html)
    if converter is None:
        raise UnsupportedFrameworkError(
            "Error: Unsupported framework. "
            "This tool currently supports: MkDocs (Material). "
            "The page does not appear to be generated by any supported framework."
        )
    return converter


def get_framework_name(html: str) -> str:
    """Return a human-readable framework name for logging."""
    if MkdocsMaterialConverter.detect(html):
        version = _mkdocs_version(html) or "mkdocs"
        return version
    return "unknown"
