"""Validate that an HTML page was generated by MkDocs Material."""

from bs4 import BeautifulSoup


MKDOCS_GENERATOR_PREFIX = "mkdocs-"


class ValidationError(Exception):
    """Raised when the page is not a MkDocs Material page."""


def is_mkdocs_material(html: str) -> bool:
    """Check if the HTML contains a meta generator tag from MkDocs."""
    soup = BeautifulSoup(html, "lxml")
    meta = soup.find("meta", attrs={"name": "generator"})
    if meta is None:
        return False
    content = meta.get("content", "")
    return content.startswith(MKDOCS_GENERATOR_PREFIX)


def get_generator_version(html: str) -> str | None:
    """Extract the full generator version string, or None if not found."""
    soup = BeautifulSoup(html, "lxml")
    meta = soup.find("meta", attrs={"name": "generator"})
    if meta is None:
        return None
    return meta.get("content", "").strip()


def validate(html: str) -> str:
    """Validate the page is MkDocs Material and return the generator string.

    Raises ValidationError if not a MkDocs Material page.
    """
    version = get_generator_version(html)
    if version is None or not version.startswith(MKDOCS_GENERATOR_PREFIX):
        raise ValidationError(
            "Error: Not a MkDocs Material page. "
            "This tool only supports pages built with MkDocs (mkdocs-material)."
        )
    return version
