"""MkDocs Material page detection."""

from bs4 import BeautifulSoup


MKDOCS_GENERATOR_PREFIX = "mkdocs-"


def detect(html: str) -> bool:
    """Return True if the HTML was generated by MkDocs (Material)."""
    soup = BeautifulSoup(html, "lxml")
    meta = soup.find("meta", attrs={"name": "generator"})
    if meta is None:
        return False
    content = meta.get("content", "")
    return content.startswith(MKDOCS_GENERATOR_PREFIX)


def get_version(html: str) -> str | None:
    """Extract the full generator version string, or None if not found."""
    soup = BeautifulSoup(html, "lxml")
    meta = soup.find("meta", attrs={"name": "generator"})
    if meta is None:
        return None
    return meta.get("content", "").strip()
