"""Abstract base class for framework converters."""

from abc import ABC, abstractmethod
from dataclasses import dataclass


@dataclass
class SidebarLink:
    """A single link extracted from the sidebar navigation."""

    href: str
    text: str
    level: int = 0  # nesting depth (0 = top-level)


class BaseConverter(ABC):
    """Interface that all framework converters must implement.

    Each supported documentation framework (MkDocs Material, Hugo Docs,
    Docusaurus, etc.) provides a concrete implementation of this class.
    """

    @staticmethod
    @abstractmethod
    def detect(html: str) -> bool:
        """Return True if html was generated by this framework."""
        ...

    @abstractmethod
    def extract_article(self, html: str, base_url: str) -> str:
        """Extract the main article content from the full page HTML.

        Returns the inner HTML of the article element.
        """
        ...

    @abstractmethod
    def convert(self, article_html: str, base_url: str = "") -> str:
        """Convert article HTML to GFM Markdown."""
        ...

    @abstractmethod
    def extract_sidebar_links(self, html: str, base_url: str) -> list[SidebarLink]:
        """Extract navigation links from the sidebar.

        Returns a list of SidebarLink objects with hierarchy info.
        """
        ...
